### ISSUE TITLE
Validate schedule input

### ISSUE THREAD

**Issue by astuyve** [serverless-components/aws-lambda-cron#1]
Right now we just validate the presence of `schedule` in the `inputs` object. It'd be great if we validated it to ensure that's a valid schedule string, either:
`rate(XYZ minutes/hours/days)`
or a valid crontab expression:
`cron(0/5 8-17 ? * MON-FRI *)`

Bonus points if we can do it accurately, without relying on third party libraries

**Comment by raydwaipayan** [comment]
I think we can do that pretty easily using regex. I would like to get my hands dirty

**Comment by astuyve** [comment]
Sounds great @raydwaipayan - feel free to tag me whenever you've got something working and I can help test it out!
